### ISSUE TITLE
Refused to Load image 

### ISSUE THREAD

**Issue by Criticalcarpet** [50UM3N/video-chat#10]
I tried to deploy my app in heroku then i created a new credential then tried to login but it gave me this error (in the below link)....
what should I do ?

![click this image for reference](https://user-images.githubusercontent.com/76092002/115338309-36cb0680-a1c0-11eb-8d06-232493ed7927.png)

**Comment by SamTheDemon** [comment]
@criticalcarpet  Can you help with Heroku Deployment? I have been trying to deploy it I keep receiving errors before deploying. would you please tell me which steps did you do? 
ixenonxi@gmail.com

**Comment by Criticalcarpet** [comment]
@SamTheDemon Yes I can Should i contact u in that email ??

**Comment by SamTheDemon** [comment]
@criticalcarpet  Yes please

**Comment by Criticalcarpet** [comment]
Yeah.. I have sent the mail... ^^ 
Let's discuss there ^^

**Comment by RahulGoel2000** [comment]
I am facing the same issue.......deployed the app and added the credentials....but then got internal server error......pls help
