### ISSUE TITLE
how can 2 different accts call

### ISSUE THREAD

**Issue by Aishani2001** [50UM3N/video-chat#11]
sir how can two different accounts call using this?

**Comment by 50UM3N** [comment]
Elaborate please

> sir how can two different accounts call using this?

Elaborate please.

**Comment by Aishani2001** [comment]
Cannot GET /https://soumen-video-calling-app.herokuapp.com/0220dbe4-8d09-441f-862b-6400e56b35fb
this is what i get when i try connecting from two different account registered
