### ISSUE TITLE
hello sir 

### ISSUE THREAD

**Issue by harzgreatest** [50UM3N/video-chat#2]
May you help me solve this problem?
after I do npm install dotenv, and run node server.js appear this!
![image](https://user-images.githubusercontent.com/81094481/111908942-be243d80-8a8d-11eb-98f8-7793d153347d.png)

**Comment by 50UM3N** [comment]
The model is being called before the connection is established. That means you doesn't provide any connection string or you write it wrong.

**Comment by harzgreatest** [comment]
> The model is being called before the connection is established. That means you doesn't provide any connection string or you write it wrong.

How to set installation connection mongodb and mongo.clients?

**Comment by 50UM3N** [comment]
I add the database setup section in the README.md. Check that to resolve.
