### ISSUE TITLE
How I can set up this connection?

### ISSUE THREAD

**Issue by harzgreatest** [50UM3N/video-chat#4]
which file should i fix it? server.js?
![image](https://user-images.githubusercontent.com/81094481/112144894-43cdf780-8c0c-11eb-9665-d374e845c918.png)
Thankyou!

**Comment by 50UM3N** [comment]
https://www.youtube.com/watch?v=wUP5kjmzgrQ

Use that video as a reference to grab the connection string and then follow the [Database Setting](https://github.com/50UM3N/video-chat#setting-database) part in README.md
