### ISSUE TITLE
Config connection

### ISSUE THREAD

**Issue by harzgreatest** [50UM3N/video-chat#5]
Sir in file server.js have require.dotenv.config
Missing file config may I know this configuration code? Is it to connect a database or what?

**Comment by 50UM3N** [comment]
Make a file name .env in the project directory and put your connection string like 

```
MONGO_URL=past your connection string
```

**Comment by harzgreatest** [comment]
> Make a file name .env in the project directory and put your connection string like
> 
> ```
> MONGO_URL=past your connection string
> ```

Done keep error :MongoParsError: no username povided in authority section

**Comment by 50UM3N** [comment]
My bad it will be MONGO_URI instead od MONGO_URL

**Comment by harzgreatest** [comment]
> My bad it will be MONGO_URI instead od MONGO_URL

MONGO_URI=mongodb+srv://admin:<admin>@cluster0.kfx8y.mongodb.net/atlasAdmin?retryWrites=true&w=majority
sir how to know name of database?  in collection.js?

**Comment by 50UM3N** [comment]
> > My bad it will be MONGO_URI instead od MONGO_URL
> 
> MONGO_URI=mongodb+srv://admin:@cluster0.kfx8y.mongodb.net/atlasAdmin?retryWrites=true&w=majority
> sir how to know name of database? in collection.js?

In that case 'atlasAdmin' is the database name. And one thing you forget to give the password of admin in between 'admin:' and '@cluster0.kfx8y.mongodb.net'

**Comment by harzgreatest** [comment]
> > > My bad it will be MONGO_URI instead od MONGO_URL
> > 
> > 
> > MONGO_URI=mongodb+srv://admin:@cluster0.kfx8y.mongodb.net/atlasAdmin?retryWrites=true&w=majority
> > sir how to know name of database? in collection.js?
> 
> In that case 'atlasAdmin' is the database name. And one thing you forget to give the password of admin in between 'admin:' and '@cluster0.kfx8y.mongodb.net'

nah now mongo error: authentication failed
![image](https://user-images.githubusercontent.com/81094481/112178130-1e50e600-8c2c-11eb-9542-aeee87539e3c.png)
Is true my database name is atlasAdmin? or I must create a database from collection.js?
