### ISSUE TITLE
Room validation failed

### ISSUE THREAD

**Issue by harzgreatest** [50UM3N/video-chat#6]
Validation Error: rooms validation failed: amdin: Path 'admin' is required
When I join with other account use by share link appear this, How to solve?

**Comment by harzgreatest** [comment]
Sir when want to peer to peer (use copy link) always error cant join in the same times

**Comment by harzgreatest** [comment]
https://soumen-video-calling-app.herokuapp.com/6e97047e-3cd3-4fa7-834b-e2041163b0b7

**Comment by Criticalcarpet** [comment]
I too got the same error 
and if i join with other account the other person's video is not visible...

**Comment by 50UM3N** [comment]
![image](https://user-images.githubusercontent.com/30142639/114594893-699a6980-9cab-11eb-87fe-cf062f59b3da.png)
Just uncomment the line having  ```port: "3000"```

**Comment by SamTheDemon** [comment]
I guess this problem still exists 
although no error showing in the terminal but this is what I get  in the browser
`Cannot GET /http://localhost:3000/9b612b4f-8dac-4b08-8b3a-c36e5ea92131`

**Comment by Criticalcarpet** [comment]
Me too.... I too tried to debug but not able to find...

**Comment by 50UM3N** [comment]
> I guess this problem still exists
> although no error showing in the terminal but this is what I get in the browser
> `Cannot GET /http://localhost:3000/9b612b4f-8dac-4b08-8b3a-c36e5ea92131`

In which browser mobile or desktop?

**Comment by SamTheDemon** [comment]
> > I guess this problem still exists
> > although no error showing in the terminal this is what I get in the browser
> > `Cannot GET /http://localhost:3000/9b612b4f-8dac-4b08-8b3a-c36e5ea92131`
> 
> In which browser mobile or desktop?

I tried it on Microsoft Edge, Google Chrome, and Opera Browser, none worked.

**Comment by Criticalcarpet** [comment]
I tried it in Google chrome , Internet Explorer, and even safari using my
friends laptop but it didn't work...

**Comment by SamTheDemon** [comment]
Let me add that even the Demo you have in README.md has the same problem

**Comment by SamTheDemon** [comment]
@50UM3N  Is there anything about the error I tried to debug but I keep getting : `UnhandledPromiseRejectionWarning: ValidationError: rooms validation failed: admin: Path "admin" is required.`

**Comment by SamTheDemon** [comment]
@50UM3N  On `server.js` on the `socket.on("join-room")` callback I saw that you only use `socket.join` on the else part of code,  and on the if and else if statements don't really have `socket.join ` i guess they should have  I tried nothing worked but maybe I tried it wrong.
