### ISSUE TITLE
Room Validation failed

### ISSUE THREAD

**Issue by Criticalcarpet** [50UM3N/video-chat#7]
I actually hosted the project locally and it worked fine.. but when i created another account and tried to join the other user didn't show up... then I checked the console and it showed that the Room validation has failed... What is the reason ??

The first issue was also stating the same thing but there was no reply.. So, I raised the second issue...

Please respond :(

**Comment by 50UM3N** [comment]
https://github.com/50UM3N/video-chat/issues/6#issuecomment-818913232
